---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: run show version on ios device
     ios_command:
       commands:
         - show version
       timeout: 30  # Set the timeout to 30 seconds (adjust as needed)
