---
- name: Create New User and Save Config on Cisco Device
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure new user
      ios_config:
        lines:
          - username admin privilege 15 secret P@ssw0rd
      register: config_output

    - name: Save configuration
      ios_command:
        commands:
          - write memory
      when: config_output.changed
