---
- name: Run show version on iOS device
  hosts: ios_devices
  gather_facts: false
  connection: network_cli
  tasks:
    - name: run show version on ios device
      ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Display show version output
      debug:
        var: show_version_output.stdout_lines
