---
- name: Run show version on remote devices
  hosts: 10.1.196.113  # Specify the target hosts or group here
  gather_facts: no  # You can set this to 'yes' if you want to gather facts

  tasks:
    - name: Execute show version command
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Display show version output
      debug:
        var: show_version_output.stdout_lines
